name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Upload ${{ matrix.target }} binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: zip
          - target: x86_64-apple-darwin
            archive: zip
          - target: aarch64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
      - name: Upload ${{ matrix.target }} Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          asset_name: image-organiser-${{ matrix.target }}.${{ matrix.archive }}
          asset_content_type: application/zip
      - name: Upload ${{ matrix.target }} Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compile.outputs.BUILT_CHECKSUM }}
          asset_name: image-organiser-${{ matrix.target }}-checksum.txt
          asset_content_type: text/plain
